### PR TITLE
Modify fuzz

### PR DESCRIPTION
**Pull request by haowqs**
- Cleanup the td-loader and td-uefi-pi fuzz
  remove  redundant code
- Modify the fuzzing.sh
  update afl run path where valid coverage report can be generated
- Update fuzzing.md
  rust toolchain update, update related content

Signed-off-by: haowei <WeiX.Hao@intel.com>

### CODE REVIEW

**Comment by jyao1** [comment]
Why we need move the location?

Please submit an issue at first with a RFC proposal at first.

**Comment by jyao1** [comment]
please resolve the conflict.

**Comment by jyao1** [comment]
please resolve the conflict.

**Review by jiangliu — APPROVED** [review]

**Comment by haowqs** [comment]
> @haowqs, Why we need move the location?
> 
> Please submit an issue at first with a RFC proposal at first.

There's no reason to move, so don't move

**Pull request closed without merging**
