### PR TITLE
td-layout: Fix potential arithmetic overflow

### PR DESCRIPTION
**Pull request by liuw1**
Fix: #396
Signed-off-by: Wei Liu <wei3.liu@intel.com>

### CODE REVIEW

**Review by jodh-intel — COMMENTED** [review]
Hi @liuw1 - Could you add some unit tests for this change?

**Comment by liuw1** [comment]
> Hi @liuw1 - Could you add some unit tests for this change?

Hi @jodh-intel It's hard to add unit test case to cover the scenario. But the MIRAI will report the warnings.

**Comment by jodh-intel** [comment]
@liuw1 - Agreed. To make it easier (more reliable) to unit-test, you could create something like:

```rust
fn validate_sections(sections: &[TdxMetadataSection]) -> Result<()> {
    // ...

    Ok(())
}
```

And then rework `is_valid_sections()` to return `true` if `validate_sections()` return `()`, or `false` on `Err()`. Then, you could reliably unit test `validate_sections()` as you could check the specified error returned.

**Review by jodh-intel — APPROVED** [review]
The change looks reasonable, but I'd still prefer some sort of UT to verify it.

**Review by jyao1 — APPROVED** [review]

**Comment by jyao1** [comment]
@liuw1 , I approved it since it follows existing pattern to fix the issue.

Please consider using "fn validate_sections(sections: &[TdxMetadataSection]) -> Result<()> {" to check instead of bool.
Please file an issue for that.

**Pull request merged**
