### PR TITLE
Add unit cases for td-layout/memslice.rs

### LINKED ISSUE #52: Add unit cases for td-layout/memslice.rs
Current there's no unit test cases for td-layout/memslice.rs, it would be better to add unit test cases for it.

### PR DESCRIPTION
**Pull request by liuw1**
Check some panic scenarios.

Fix #52

Signed-off-by: Wei Liu <wei3.liu@intel.com>

### CODE REVIEW

**Comment by jiangliu** [comment]
It would be great to also add some successful test cases to validate the functionality.

**Comment by liuw1** [comment]
> It would be great to also add some successful test cases to validate the functionality.
Thanks. Add test cases to validate the functionality.

**Comment by liuw1** [comment]
I have updated the PR and added test cases to validate the functionality.

**Comment by jiangliu** [comment]
The td-layout has already been merged into the main branch, so should this PR target the main branch?
Or will we first merge it into staging then another PR to merge it into main branch?

**Comment by liuw1** [comment]
We can merge it into staging firstly and I will add another PR to merge it into main branch later.

**Review by jiangliu — APPROVED** [review]

**Review by jodh-intel — APPROVED** [review]
Thanks @liuw1!

lgtm

**Pull request merged**
