### PR TITLE
td-shim: fix a dependency issue about td-layout

### PR DESCRIPTION
**Pull request by jiangliu**
Fix a compilation failure caused by incorrect dependency.

Fixes: #95

Signed-off-by: Liu Jiang <gerry@linux.alibaba.com>

### CODE REVIEW

**Comment by xiaoyuxlu** [comment]
Two other ways are available:

1.  Provide a unified features at compile time. 

```
TD_SHIM_FEATURES=" --features=main,tdx"
TD_SHIM_TOOL_FEATURES=" --features=td-shim/main,td-shim/tdx,td-shim/default"
cargo build --verbose -Zbuild-std=core,compiler_builtins,alloc -Zbuild-std-features=compiler-builtins-mem --target x86_64-unknown-uefi --release -p ${TD_SHIM} ${TD_SHIM_FEATURES}
cargo build --verbose -Zbuild-std=core,alloc,compiler_builtins -Zbuild-std-features=compiler-builtins-mem --target x86_64-unknown-uefi --release -p ${PAYLOAD_NAME} ${TD_SHIM_FEATURES}
cargo run --verbose -p td-shim-tools --bin td-shim-ld ${TD_SHIM_TOOL_FEATURES} -- target/x86_64-unknown-uefi/release/ResetVector.bin target/x86_64-unknown-uefi/release/${TD_SHIM}.efi $PAYLOAD_BIN -o target/x86_64-unknown-uefi/release/final.bin
```

2. add `td-shim/default features` to td-shim-tool `td-shim-tools/Cargo.toml`:

```
[features]
default = ["boot-kernel", "enroller", "linker", "signer", "td-shim/default"]
```

Which do you think is the best?

**Comment by jiangliu** [comment]
> cargo run --verbose -p td-shim-tools --bin td-shim-ld ${TD_SHIM_TOOL_FEATURES} -- target/x86_64-unknown-uefi/release/ResetVector.bin target/x86_64-unknown-uefi/release/${TD_SHIM}.efi $PAYLOAD_BIN -o target/x86_64-unknown-uefi/release/final.bin

I followed you steps, but without the "TD_SHIM_TOOL_FEATURES" flag set.
```
cargo build --verbose -Zbuild-std=core,compiler_builtins,alloc -Zbuild-std-features=compiler-builtins-mem --target x86_64-unknown-uefi --release -p td-shim --features=tdx,main
cargo build --verbose -Zbuild-std=core,compiler_builtins,alloc -Zbuild-std-features=compiler-builtins-mem --target x86_64-unknown-uefi --release -p td-payload --features=tdx,main
cargo run --verbose -p td-shim-tools --bin td-shim-ld -- target/x86_64-unknown-uefi/release/ResetVector.bin target/x86_64-unknown-uefi/release/td-shim.efi target/x86_64-unknown-uefi/release/td-payload.efi -o target/x86_64-unknown-uefi/release/final.bin
```

So still not sure about why we need the "TD_SHIM_TOOL_FEATURES".

**Comment by xiaoyuxlu** [comment]
Because td-shim-tool depends on td-shim. If the features of these two components are inconsistent, it may cause problems in generating the image. 
It is assumed that the structure size of the td-shim varies according to the feature. td-shim uses features A but td-shim-tool does not use features A. In this way, the size of a structure in td-shim and td-shim-tool will be inconsistent. It may cause problems with the image generated by td-shim-tools. Am I expressing that clearly?

**Comment by jiangliu** [comment]
> Because td-shim-tool depends on td-shim. If the features of these two components are inconsistent, it may cause problems in generating the image. It is assumed that the structure size of the td-shim varies according to the feature. td-shim uses features A but td-shim-tool does not use features A. In this way, the size of a structure in td-shim and td-shim-tool will be inconsistent. It may cause problems with the image generated by td-shim-tools. Am I expressing that clearly?

Good point! It must keep consistence between td-shim and td-shim-tools.

There are several design goals with the td-shim crate:
1) td-shim is both a library and a binary. The `main` feature is used to control dependencies for the binary.
2) the td-shim library follows the td-shim spec, and should define all external visible behaviors.
3) the td-shim library should compatible with stable rust toolchains, so we could build td-rust-tools with stable tool chains.

With above design goals,
1) we should not enable td-shim/main feature for td-shim-tools
2) we may keep the default features for td-shim/td-shim-tools in sync, so it works with the default configuration.
3) end user takes the responsibility to ensure consistent feature flags for td-shim/td-shim-tools.

**Comment by xiaoyuxlu** [comment]
> > Because td-shim-tool depends on td-shim. If the features of these two components are inconsistent, it may cause problems in generating the image. It is assumed that the structure size of the td-shim varies according to the feature. td-shim uses features A but td-shim-tool does not use features A. In this way, the size of a structure in td-shim and td-shim-tool will be inconsistent. It may cause problems with the image generated by td-shim-tools. Am I expressing that clearly?
> 
> Good point! It must keep consistence between td-shim and td-shim-tools.
> 
> There are several design goals with the td-shim crate:
> 
>     1. td-shim is both a library and a binary. The `main` feature is used to control dependencies for the binary.
> 
>     2. the td-shim library follows the td-shim spec, and should define all external visible behaviors.
> 
>     3. the td-shim library should compatible with stable rust toolchains, so we could build td-rust-tools with stable tool chains.
> 
> 
> With above design goals,
> 
>     1. we should not enable td-shim/main feature for td-shim-tools
> 
>     2. we may keep the default features for td-shim/td-shim-tools in sync, so it works with the default configuration.
> 
>     3. end user takes the responsibility to ensure consistent feature flags for td-shim/td-shim-tools.

That's clear, thanks.

Reviewed-by: Xiaoyu Lu <xiaoyu1.lu@intel.com>

**Pull request merged**
